/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import TSPFicheros.TSPfichero;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author rubco
 */
public class BarraSuperiorPanel extends javax.swing.JPanel {

    /**
     * Creates new form BarraSuperiorPanel
     */
    public BarraSuperiorPanel() {
        initComponents();
        setLayout(null);

        ficheroCargado.setBounds(30, 25, 250, 20);
        ficheroCargado.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        cambiarLabel();
        this.add(ficheroCargado);

        BotonBarraSuperior boton = new BotonBarraSuperior(); // Mejor pasar texto
        boton.setBounds(580, 15, 140, 35);
        this.add(boton);

        // 💥 LLAMAMOS AL MÉTODO SIN RETORNO DE VALOR 💥
        cargarBotonBasuraAsincrono();
    }

// ⚠️ El método ya NO devuelve BotonBasura
    private void cargarBotonBasuraAsincrono() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            try {
                // 1. CREACIÓN DEL BOTÓN (ocurre más tarde, liberando el hilo principal)
                ImageIcon iconoBasura = new ImageIcon(getClass().getResource("/imagenes/papelera.png"));
                BotonBasura basura = new BotonBasura(iconoBasura);
                basura.setBounds(730, 15, 35, 35);

                // 2. ADICIÓN DEL ACTION LISTENER (AQUÍ ES DONDE EL BOTÓN EXISTE)
                basura.addActionListener(e -> {
                    MenuPrincipal.file = new TSPfichero();
                    cambiarLabel();
                });

                // 3. AÑADIR A LA INTERFAZ Y REDIBUJAR
                this.add(basura);
                this.revalidate();
                this.repaint();

            } catch (Exception e) {
                System.err.println("Error al cargar el icono de basura: " + e.getMessage());
                e.printStackTrace();
            }
        });
    }

    private static JLabel ficheroCargado = new JLabel();

    public JLabel getLabel() {
        return ficheroCargado;
    }

    public static void cambiarLabel() {
        if (MenuPrincipal.file.getVacio()) {
            ficheroCargado.setForeground(Color.red);
            ficheroCargado.setText("NO HAY DATASET CARGADO");
        } else {
            ficheroCargado.setForeground(Color.BLACK);
            ficheroCargado.setText(MenuPrincipal.file.getNAME());
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        g.setColor(new Color(220, 220, 220));
        int x1 = 0;
        int y1 = 65;
        int x2 = 800;
        int y2 = 65;

        g.drawLine(x1, y1, x2, y2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 66));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
