/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author rubco
 */
public class BotonesPanel extends javax.swing.JPanel {

    /**
     * Creates new form BotonesPanel
     */
    private BotonBarraLateral datasetBoton;
    private BotonBarraLateral crearDatasetBoton;
    private BotonBarraLateral comprobarEstrategiasBoton;
    private BotonBarraLateral compararEstrategiasBoton;
    private BotonBarraLateral comparar2EstrategiasBoton;
    
    
    public BotonesPanel() {
        initComponents();
        
        datasetBoton = new BotonBarraLateral("Dataset");
        datasetBoton.setBounds(0, 110, 199, 40);
        this.add(datasetBoton);
        
        crearDatasetBoton = new BotonBarraLateral("Crear Fichero TSP Aleatorio");
        crearDatasetBoton.setBounds(0, 150, 199, 40);
        this.add(crearDatasetBoton);
        
        comprobarEstrategiasBoton = new BotonBarraLateral("Comprobar Estrategias");
        comprobarEstrategiasBoton.setBounds(0, 190, 199, 40);
        this.add(comprobarEstrategiasBoton);
        
        compararEstrategiasBoton = new BotonBarraLateral("Comparar Estrategias");
        compararEstrategiasBoton.setBounds(0, 230, 199, 40);
        this.add(compararEstrategiasBoton);
        
        comparar2EstrategiasBoton = new BotonBarraLateral("Comparar 2 Estrategias");
        comparar2EstrategiasBoton.setBounds(0, 270, 199, 40);
        this.add(comparar2EstrategiasBoton);
               
        
        
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        
        //g.setColor(new Color(240,238,239));
        g.setColor(new Color(220,220,220));
        int x1 = 0;
        int y1 = 65;
        int x2 = 200;
        int y2 = 65;
        
        g.drawLine(x1, y1, x2, y2);
        
        x1 = 199;
        y1 = 0;
        x2 = 199;
        y2 = 700;
        g.drawLine(x1, y1, x2, y2);
        
        x1 = 0;
        y1 = 635;
        x2 = 200;
        y2 = 635;
        g.drawLine(x1, y1, x2, y2);
        
        try{
           Image imagen = new ImageIcon(getClass().getResource("/imagenes/logoGen.png")).getImage();
           
           g.drawImage(imagen,5, nombreLogo.getY() - 12, 50,50,this);
           
        }catch (Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLogo = new javax.swing.JLabel();
        miNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 244, 245));
        setForeground(new java.awt.Color(195, 205, 205));
        setPreferredSize(new java.awt.Dimension(200, 700));

        nombreLogo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        nombreLogo.setForeground(new java.awt.Color(0, 0, 0));
        nombreLogo.setText("TSP Ficheros");

        miNombre.setBackground(new java.awt.Color(204, 204, 204));
        miNombre.setForeground(new java.awt.Color(153, 153, 153));
        miNombre.setText("Rubén Conde Quintero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nombreLogo)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(miNombre)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nombreLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, Short.MAX_VALUE)
                .addComponent(miNombre)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel miNombre;
    private javax.swing.JLabel nombreLogo;
    // End of variables declaration//GEN-END:variables
}
