/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import Algoritmos.DyV;
import Algoritmos.DyVMejorado;
import Algoritmos.Exhaustivo;
import Algoritmos.ExhaustivoPoda;
import Utils.Solucion;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author rubco
 */
public class ComprobarEstrategiasPanel extends javax.swing.JPanel {

    private TablaRender tabla;
    private DefaultTableModel model; // Necesario para actualizar los datos

    

    /**
     * Creates new form ComprobarEstrategiasPanel
     */
    public ComprobarEstrategiasPanel() {
        initComponents();

        // 💥 CORRECCIÓN 1: Usar BorderLayout para el panel para que la tabla se ajuste
        setLayout(null);
        setBackground(Color.WHITE);

        // Título (Añadido en el Norte, fuera del área de la tabla)
        JLabel titulo = new JLabel("Comprobar Estrategias");
        titulo.setFont(new Font("Segoe UI Semibold", Font.BOLD, 28));
        titulo.setForeground(Color.BLACK);
        titulo.setBounds(20, 40, 300, 40);
        add(titulo);

        tabla = new TablaRender();
        tabla.setBounds(20, 200, 740, 200);
        model = new DefaultTableModel(new Object[]{"Nombre", "Punto 1", "Punto 2", "Distancia", "Calculadas", "Tiempo"}, 0);
        tabla.setModel(model);

        JTableHeader header = tabla.getTableHeader();
        
        header.setBounds(19, 150, 741, 50); // justo encima de la tabla
        
        this.add(header);
        this.add(tabla);
    }
    
    public void actualizarTabla(){
        model.setRowCount(0);
        
        List<Solucion> solus = new ArrayList<>();
        if(MenuPrincipal.file == null || MenuPrincipal.file.getVacio()){
            
        }else{
            Exhaustivo ex = new Exhaustivo(MenuPrincipal.file.getNodos());
            ExhaustivoPoda exp = new ExhaustivoPoda(MenuPrincipal.file.getNodos());
            DyV dy = new DyV(MenuPrincipal.file.getNodos());
            DyVMejorado dym = new DyVMejorado(MenuPrincipal.file.getNodos());
            
            solus.add(ex.calcularDistanciaMasCorta());
            solus.add(exp.calcular());
            solus.add(dy.calcular());
            solus.add(dym.calcular());
        }
        
        for(int i = 0; i < solus.size(); i++){
            Solucion sol = solus.get(i);
            
            model.addRow(new Object[]{sol.getNombre(), sol.getP1().toString(), sol.getP2().toString(),"  " + sol.getDistancia(),"  " + sol.getNCalculadas(),"  " + sol.getTiempo()});
        }
    }

    /**
     * This method is called from within t"he constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
