/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author rubco
 */
public class DatasetPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatasetPanel
     */
    
    
    
    public DatasetPanel() {
        initComponents();
        this.setBounds(201, 67, 799, 670);

        JLabel titulo = new JLabel("Dataset");
        titulo.setFont(new Font("Segoe UI Semibold", Font.BOLD, 28));
        titulo.setForeground(Color.BLACK);
        titulo.setBounds(20, 40, 200, 30);
        this.add(titulo);

        BotonBarraSuperior cargarFicheroBoton = new BotonBarraSuperior();
        cargarFicheroBoton.setText("Cargar Fichero");
        cargarFicheroBoton.setBounds(540, 38, 220, 45);
        cargarFicheroBoton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirDialogoArchivo();
            }
        });
        this.add(cargarFicheroBoton);

        BotonBarraSuperior generarDatasetBoton = new BotonBarraSuperior();
        generarDatasetBoton.setText("Generar Dataset");
        generarDatasetBoton.setBounds(540, 98, 220, 45);
        this.add(generarDatasetBoton);

    }

    private void abrirDialogoArchivo() {
        JFileChooser fileChooser = new JFileChooser();
        File carpeta = new File("src/data");
        fileChooser.setCurrentDirectory(carpeta);

        int resultado = fileChooser.showOpenDialog(MenuPrincipal.menuPrincipal);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            try {
                MenuPrincipal.file.leerFichero(archivoSeleccionado.getName());
                BarraSuperiorPanel.cambiarLabel();
                System.out.println("Archivo seleccionado: " + archivoSeleccionado.getName());
            } catch (IOException e) {
                System.out.println("Error: " + e.getMessage());
            }
        } else {
            System.out.println("No se seleccionó ningun archivo");
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponents(g);

        g.setColor(new Color(220, 220, 220));
        int x1 = 0;
        int y1 = getHeight() - (736 - 635);
        int x2 = 800;
        int y2 = getHeight() - (736 - 635);
        g.drawLine(x1, y1, x2, y2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
