/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Algoritmos.ExhaustivoPoda;
import TSPFicheros.TSPfichero;
import Utils.Punto;
import Utils.Solucion;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author rubco
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        getContentPane().setBackground(new Color(255,255,255));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1000, 736));
        setMinimumSize(new Dimension(1000, 700));
        setMaximumSize(new Dimension(1000, 736));
        
        pack();
        file = null;
        nombreFichero = "NO HAY FICHERO CARGADO";
        
        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 736));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static TSPfichero file;
    public static String nombreFichero;
    public static BotonesPanel bP;
    public static BarraSuperiorPanel bS;
    public static CardLayout cardLayout = new CardLayout();
    public static JPanel contentPanel = new JPanel();
    public static MenuPrincipal menuPrincipal = new MenuPrincipal();
    public static DatasetPanel dP;
    public static BarraInferiorPanel bI;
    public static Solucion sol;
    public static ComprobarEstrategiasPanel cE;
    public static CompararEstrategiasPanel compaEstra;
    public static Comparar2EstrategiasPanel c2e;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        contentPanel.setLayout(cardLayout);
        contentPanel.setBounds(200, 66, 800, 568);
        file = new TSPfichero();
        
        
                
        bP = new BotonesPanel();
        bP.setBounds(0, 0, 200, 700);
        menuPrincipal.add(bP);
        
        dP = new DatasetPanel();
        cE = new ComprobarEstrategiasPanel();
        compaEstra = new CompararEstrategiasPanel();
        c2e = new Comparar2EstrategiasPanel();
        
        bS = new BarraSuperiorPanel();
        bS.setBounds(200,0,800, 66);
        menuPrincipal.add(bS);
        
        
        contentPanel.add(dP, "DATASET");
        contentPanel.add(cE, "COMPROBAR");
        contentPanel.add(compaEstra, "COMPARAR");
        contentPanel.add(c2e, "COMPARAR2");
        cardLayout.show(contentPanel, "DATASET");
        
        menuPrincipal.add(contentPanel);
        
        bI = new BarraInferiorPanel();
        bI.setBounds(200,634, 800, 102);
        bI.setBackground(Color.WHITE);
        menuPrincipal.add(bI);
        sol = new Solucion();
        
        menuPrincipal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
